### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by ipkpjersi** [RyoIkarashi/tutsplus-dl#1]
Hi, do you think you can add subtitle support? Thanks.

**Comment by ryoikarashi** [comment]
Hi, @ipkpjersi 
What do you mean by 'subtitle support'?
Could you explain it in more detail?

**Comment by ipkpjersi** [comment]
Thank you for responding so quickly! I mean by subtitle support, closed-caption support. Some courses have closed-captions which means you can see the text that the author of the videos is saying. I am sure there is some way to download subtitles so I am wondering if this feature can be implemented. Thank you.

**Comment by ryoikarashi** [comment]
@ipkpjersi 
Okay I got it.
I'll be looking into it and maybe work on it when I have time. :)

**Comment by ipkpjersi** [comment]
Glad to hear it, thank you.

**Comment by ipkpjersi** [comment]
Hi @RyoIkarashi any idea when you will have time to implement this? I would absolutely love to have this feature implemented, it would be great to have. I am not sure how difficult it would be, I hope it would be easy to add. Thank you.

**Comment by IsmoilSafarov** [comment]
Assalomu alaykum @RyoIkarashi 
Can you help me?  Handling Error:

Traceback (most recent call last):
  File "dl.py", line 232, in <module>
    downloader.download()
  File "dl.py", line 133, in download
    course_soup = self.get_soup(self.certain_course_url)
  File "dl.py", line 58, in get_soup
    soup = BeautifulSoup(c, 'lxml')
  File "C:\Users\Ismoil Safarov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by TeamBrekele** [comment]
> Assalomu alaykum @RyoIkarashi
> Can you help me? Handling Error:
> 
> Traceback (most recent call last):
> File "dl.py", line 232, in 
> downloader.download()
> File "dl.py", line 133, in download
> course_soup = self.get_soup(self.certain_course_url)
> File "dl.py", line 58, in get_soup
> soup = BeautifulSoup(c, 'lxml')
> File "C:\Users\Ismoil Safarov\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bs4__init__.py", line 165, in **init**
> % ",".join(features))
> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

pip install lxml
