### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019'

### ISSUE THREAD

**Issue by harryqt** [RyoIkarashi/tutsplus-dl#3]
```
Traceback (most recent call last):
  File "dl.py", line 234, in <module>
    downloader.downloadAll()
  File "dl.py", line 200, in downloadAll
    self.print_course_title(course_title)
  File "dl.py", line 84, in print_course_title
    print('\tCourse Title: ' + course_title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 25: ordinal not in range(128)
```

**Comment by harryqt** [comment]
Sorry, I was using Python 2.
Python 3 seems have no issue.
